### ISSUE TITLE
1.16.1 Unable to Backup Server

### ISSUE THREAD

**Issue by AgentEddie99** [Exolius/SimpleBackup#33]
Hi I have updated my server from 1.14.4 to 1.16.1 when the server does a backup I get the below in the console

>sbackup
[21:12:19] [Server thread/INFO]: [SVRMC01-FAM] Backup starting...
[21:12:19] [Server thread/WARN]: A manual (plugin-induced) save has been detected while server is configured to auto-save. This may affect performance.
[21:12:19] [Thread-98/INFO]: [SimpleBackup] Backing up .\world\.
[21:12:31] [Thread-98/WARN]: [SimpleBackup] Unable to backup file: C:\Minecraft Server\.\world\.\session.lock(The process cannot access the file because another process has locked a portion of the file)
[21:12:31] [Thread-98/INFO]: [SimpleBackup] Backing up .\world_nether\.
[21:12:31] [Thread-98/WARN]: [SimpleBackup] duplicate entry: data/raids.dat
java.util.zip.ZipException: duplicate entry: data/raids.dat
        at java.util.zip.ZipOutputStream.putNextEntry(Unknown Source) ~[?:1.8.0_251]
        at com.exolius.simplebackup.ZipBackup.zipFiles(ZipBackup.java:59) ~[SimpleBackup-1.8.jar:?]
        at com.exolius.simplebackup.ZipBackup.zipFiles(ZipBackup.java:55) ~[SimpleBackup-1.8.jar:?]
        at com.exolius.simplebackup.ZipBackup.zipFiles(ZipBackup.java:55) ~[SimpleBackup-1.8.jar:?]
        at com.exolius.simplebackup.ZipBackup.createBackup(ZipBackup.java:28) ~[SimpleBackup-1.8.jar:?]
        at com.exolius.simplebackup.SimpleBackup.doBackup(SimpleBackup.java:189) [SimpleBackup-1.8.jar:?]
        at com.exolius.simplebackup.Commands$1.run(Commands.java:24) [SimpleBackup-1.8.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[21:12:32] [Server thread/INFO]: [SVRMC01-FAM] Backup completed successfully.

I have looked over the code and I can't see anything wrong, are you able to have a look at it?

**Comment by RoboMWM** [comment]
interesting, what does your config look like?

**Comment by AgentEddie99** [comment]
I know right, config fike below.

backup-interval-hours: 1.0
backup-folders:
- server.properties
- permissions.yml
- whitelist.json
- ops.json
- logs
- plugins
- usercache.json
backup-file: D:\Games\Backups\Minecraft\Minecraft Server Backups\Vanilla Server
backup-date-format: yyyy-MM-dd-HH-mm-ss
backup-empty-server: false
disable-zipping: false
broadcast-message: true
backup-message: '[SVRMC01-FAM]'
custom-backup-message: Backup starting...
custom-backup-message-end: Backup completed successfully.
backup-completed-hook: ''
delete-schedule:
  intervals:
  - 1d
  - 3d
  - 4w
  - 30w
  interval-frequencies:
  - 4h
  - 1d
  - 5d
  - 30d

**Comment by RoboMWM** [comment]
For `backup-folders:` why are you putting specific files? This list is only meant for folders afaik (unless it actually works with specific files?)

Try with the defaults (which I think is just `plugins`) here.

**Comment by curtp** [comment]
I'm having the same issue. I disabled the zip feature and according to the logs it was backing up all worlds. When I went into the backups folder then into the folder there was a mix of files from multiple worlds instead of a directory for each world, which is what I expected.

Here are the logs from the backup process:
[19:48:08] [Server thread/INFO]: [SimpleBackup] Backup starting
[19:48:08] [Thread-20/INFO]: [SimpleBackup] Backing up ./world/.
[19:48:08] [Thread-20/INFO]: [SimpleBackup] Backing up ./world_nether/.
[19:48:08] [Thread-20/INFO]: [SimpleBackup] Backing up ./world_the_end/.
[19:48:08] [Thread-20/INFO]: [SimpleBackup] Backing up ./foobar_1/.
[19:48:08] [Thread-20/INFO]: [SimpleBackup] Backing up ./foobar_2/.
[19:48:08] [Thread-20/INFO]: [SimpleBackup] Backing up ./foobar_3/.
[19:48:09] [Thread-20/INFO]: [SimpleBackup] Backing up ./foobar_4/.
[19:48:11] [Thread-20/INFO]: [SimpleBackup] Backing up ./foobar_5/.
[19:48:12] [Server thread/INFO]: [SimpleBackup] Backup completed

The files are being backed up to the backups folder with a date/time stamp for the directory name. Here is the contents of the directory. It looks like the files for a mix of multiple worlds.

[/opt/minecraft/backups/2020-07-09-19-48-08]$ ls
advancements  data  datapacks  DIM1  DIM-1  level.dat  level.dat_old  playerdata  poi  region  session.lock  stats  uid.dat

When I enable zip, it doesn't make it past the world_nether backup. That is where it throws an exception about a duplicate entry for session.lock.

**Comment by RoboMWM** [comment]
Yea, I tested this yesterday briefly with my existing config (and fork of the plugin) and it's backing up each world folder directly to the root of the zip instead of within a folder. I wonder what changed in the bukkit API...

**Comment by AgentEddie99** [comment]
I tested with out the additional files and it does the same thing. And the ZIPing is also all in the root of the zip folder not like it was with folders for the seperate worlds etc.

I have attached photos of the errors in the console and the config file settings.

![2020-07-11_10h23_24](https://user-images.githubusercontent.com/56587828/87212580-a58e5000-c362-11ea-8166-326f88d91b88.png)
![2020-07-11_10h23_33](https://user-images.githubusercontent.com/56587828/87212582-a6bf7d00-c362-11ea-8e0c-fa9e7d286217.png)

**Comment by RoboMWM** [comment]
A cursory look at the code suggests that it shouldn't have changed... so something did in 1.16 and idk if I feel like debugging Bukkit methods across different versions...

**Comment by AgentEddie99** [comment]
Meaning that the version is not going to work on 1.16.1?

**Comment by AgentEddie99** [comment]
Meaning that the version is not going to work on 1.16.1?
